Archetypes.Add("tiger", {
    "main": Job.WAR,
    "secondary": Job.WAR,
    "model": 0x0000340100000000000000000000000000000000, // should probably simply
    "ecosystem": Ecosystem.Beast,
    "speed": 60,
    "agressive": true,
    "linking": false,
    "detection method": "scent",
    "roam behavior": 0,
    "attack delay": 0,
    "charmable": true,
    "entityFlags?": 0,
    "namePrefix?": 0,
    "str": 4,
    "dex": 3,
    "vit": 4,
    "agi": 4,
    "int": 6,
    "mnd": 4,
    "chr": 4,
    "defrank": 3,
    "evarank": 3,
    "attrank": 0,
    "accrank": 4,
    "fire_res": 1.25,
    "ice_res": 0.75,
    "lightning_res": 1.25,
    "abilities": [
        "Claw Cyclone",
        "Razor Fang",
        "Roar",
    ],
})
